"""
Multi-format Export Service (ZIP, Markdown, JSON, SQL, OpenAPI)
"""

import io
import json
import zipfile
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session
from app.models.project import Project
from app.models.artifact import Artifact
from app.models.requirement import Requirement


class ExportService:
    @staticmethod
    def export_project_bundle(db: Session, project_id: str, format_type: str = "zip") -> Any:
        project = db.query(Project).filter(Project.id == project_id).first()
        artifacts = db.query(Artifact).filter(Artifact.project_id == project_id).all()
        req = db.query(Requirement).filter(Requirement.project_id == project_id).first()

        if not project:
            raise ValueError("Project not found")

        if format_type == "json":
            bundle: Dict[str, Any] = {
                "project": {
                    "name": project.name,
                    "description": project.description,
                    "industry": project.industry,
                    "scale_tier": project.scale_tier,
                    "tech_preferences": project.tech_preferences,
                    "status": project.status
                },
                "requirements": req.finalized_srs or req.project_summary if req else {},
                "artifacts": [
                    {
                        "type": a.artifact_type,
                        "title": a.title,
                        "version": a.version,
                        "content": a.content
                    } for a in artifacts
                ]
            }
            return json.dumps(bundle, indent=2)

        elif format_type == "markdown":
            md_lines = [
                f"# ArchAI Software Blueprint: {project.name}",
                f"**Industry**: {project.industry} | **Scale**: {project.scale_tier}",
                f"**Tech Stack**: {project.tech_preferences}",
                "",
                "## Project Overview",
                project.description or "",
                "",
                "---",
            ]
            for a in artifacts:
                md_lines.append(f"\n## {a.title} ({a.artifact_type})\n")
                if isinstance(a.content, str):
                    md_lines.append(a.content)
                else:
                    md_lines.append(f"```json\n{json.dumps(a.content, indent=2)}\n```")
            return "\n".join(md_lines)

        elif format_type == "zip":
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
                written_files: set[str] = set()

                def safe_writestr(filename: str, data: str | bytes):
                    if filename not in written_files:
                        zf.writestr(filename, data)
                        written_files.add(filename)

                # Add README
                readme_content = f"# {project.name} - Architecture Documentation\nGenerated by ArchAI.\n\nDescription:\n{project.description}\n"
                safe_writestr("README.md", readme_content)

                # Add each artifact (sort by version ascending so latest versions overwrite if needed or write distinct version filenames)
                for a in artifacts:
                    if (a.artifact_type == "SQL" or "ddl_script" in str(a.content)) and isinstance(a.content, dict) and "ddl_script" in a.content:
                        safe_writestr("schema.sql", a.content["ddl_script"])
                    elif a.artifact_type == "API_SPEC" and isinstance(a.content, dict):
                        safe_writestr("openapi.json", json.dumps(a.content.get("openapi_spec", a.content), indent=2))
                    elif a.artifact_type == "TECHNICAL_DOC" and isinstance(a.content, dict):
                        if "system_architecture_document" in a.content:
                            safe_writestr("SOFTWARE_ARCHITECTURE_DOCUMENT.md", a.content.get("system_architecture_document", ""))
                        if "software_requirements_specification" in a.content:
                            safe_writestr("REQUIREMENTS_SPECIFICATION.md", a.content.get("software_requirements_specification", ""))
                        if "developer_onboarding_guide" in a.content:
                            safe_writestr("DEVELOPER_GUIDE.md", a.content.get("developer_onboarding_guide", ""))
                    elif a.artifact_type == "DEPLOYMENT_PLAN" and isinstance(a.content, dict):
                        if "docker_compose_yaml" in a.content:
                            safe_writestr("docker-compose.yml", a.content["docker_compose_yaml"])
                        if "github_actions_ci_yaml" in a.content:
                            safe_writestr("ci.yml", a.content["github_actions_ci_yaml"])

                # Include Full Synthesized Software Codebase
                try:
                    from app.services.codebase_synthesizer import CodebaseSynthesizerService
                    codebase_data = CodebaseSynthesizerService.generate_codebase(db, project_id)
                    for code_file in codebase_data.get("files", []):
                        safe_writestr(code_file["path"], code_file["content"])
                except Exception as e:
                    pass

                # Save full json artifact
                for a in artifacts:
                    safe_writestr(f"artifacts/{a.artifact_type.lower()}_v{a.version}.json", json.dumps(a.content, indent=2))

            zip_buffer.seek(0)
            return zip_buffer.getvalue()

        return None
